config/routes.rb
Rails.application.routes.draw do
  root to: 'gmaps#index'
  devise_for :members
  get 'members/downloadpdf/download', to: 'members#downloadpdf'

  resources :members, only: [:show] do
    collection do
      get :search
      get :dispatching
    end
  end
  resources :gmaps do
    collection do
      get :confirm
      post :check
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/gmap.rb
class Gmap < ApplicationRecord
  require 'digest/md5'
  validates :title, presence: true, length: { minimum: 1, maximum: 25 }
  validates :coment, presence: true, length: { minimum: 1, maximum: 255 }
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :image, presence: true

  before_save :encrypt_magic_word

  def encrypt_magic_word
    if magic_word.present?
      self.magic_word = Digest::MD5.hexdigest(self.magic_word)
    end
  end

  belongs_to :member
  mount_uploader :image, ImageUploader
end

app/controllers/gmaps_controller.rb
class GmapsController < ApplicationController
  before_action :set_gmap, only: %i[edit show update]
  before_action :authenticate_member!, only: %i[new edit update destroy]

  def index
    @gmaps = Gmap.where(magic_word: '')
  end

  def show
  end

  def new
    if params[:back]
      @gmap = current_member.gmaps.build(gmap_params)
    else
      @gmap = Gmap.new
    end
  end

  def edit
  end

  def check
    @gmap = current_member.gmaps.build(gmap_params)
    render :new if @gmap.invalid?
  end

  def create
    @gmap = current_member.gmaps.build(gmap_params)
      if @gmap.save
        flash[:success] = 'マーカーを作るのに成功しました'
        redirect_to root_path
      else
        flash[:danger] = 'マーカーを作るのに失敗しました'
        render :new
      end
  end

  def update
    if @gmap.update(gmap_params)
      redirect_to @gmap, flash[:success] = 'Gmapデータがアップデートされました'
    else
      render :edit
    end
  end

  def destroy
    @gmap = current_member.gmaps.find(params[:q])
    if @gmap.member_id == current_member.id
      @gmap.destroy
      @status = 200
    else
      @status = 400
    end
    render json: { gmap: @gmap }, status: @status
  end

  private

  def set_gmap
    @gmap = current_member.gmaps.find(params[:id])
  end

  def gmap_params
    params.require(:gmap).permit(:title, :coment,
                                 :magic_word, :latitude, :longitude, :image)
  end

end

app/views/gmaps/_form.html.erb
<%= form_with(model: @gmap, local: true, html: {multipart: true} ,url: choose_new_or_edit ) do |form| %>
<% if @gmap.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@gmap.errors.count, "error") %>
    prohibited this gmap from being saved:</h2>
  <ul>
    <% @gmap.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="field">
    <%= form.hidden_field :latitude, id: :gmap_latitude %>
  </div>
  <div class="field">
    <%= form.hidden_field :longitude, id: :gmap_longitude %>
  </div>
  <div class="field form-group">
    <%= form.label :"タイトル" %>
    <%= form.text_field :title,id: :gmap_title ,class: "form-control"%>
  </div>
  <div class="field form-group">
    <%= form.label :"コメント" %><br>
    <%= form.text_area :coment, id: :gmap_coment ,size: "40x4",class: "form-control"%>
  </div>
  <div class="field form-group">
    <%= form.label :"合言葉" %>
    <%= form.text_field :magic_word,id: :gmap_magic ,class: "form-control"%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

app/views/gmaps/edit.html.erb
<h1>Gmapの編集</h1>
<%= render 'form', gmap: @gmap %>

app/views/gmaps/index.html.erb
<h1>Gmaps</h1>
<div id="gmaps"></div>
<br>
<%= javascript_tag do %>
  window.addresses = <%= raw @gmaps.to_json %>;
<% end %>
<div class="text-center"><strong><%= link_to 'マーカー情報を登録する',dispatching_members_path ,class: "marker_description btn btn-primary"%></strong></div>
<p>
  <script type="text/javascript">
    initMap();
  </script>
  <%#= javascript_include_tag 'markers.js', 'data-turbolinks-track' => true %>
</p>

app/views/gmaps/new.html.erb
<h1 class="text-center">New Gmap</h1>
<script>
  if (navigator.geolocation) {
    alert("この端末では位置情報が取得できます");
    navigator.geolocation.getCurrentPosition((position) => {
      document.getElementById('gmap_latitude').value = position.coords.latitude;
      document.getElementById('gmap_longitude').value = position.coords.longitude;
    }),
    function (error) {
      switch (error.code) {
        case 1:
          alert("位置情報の利用が許可されていません");
          break;
        case 2:
          alert("現在位置が取得できませんでした");
          break;
        case 3:
          alert("タイムアウトになりました");
          break;
        default:
          alert("その他のエラー(エラーコード:" + error.code + ")");
          break;
      }
    }
  } else {
    alert("この端末では位置情報が取得できません");
  }
</script>

<% if @gmap.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@gmap.errors.count, "error") %>
      Gmapsは保存されていません:</h2>
    <ul>
      <% @gmap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with(model: @gmap=Gmap.new, local: true, html: {multipart: true}) do |form| %>
  <div class="field">
    <%= form.hidden_field :latitude, id: :gmap_latitude %>
  </div>
  <div class="field">
    <%= form.hidden_field :longitude, id: :gmap_longitude %>
  </div>
  <div class="field form-group">
    <%= form.label :"タイトル" , class: "center-block"%>
    <%= form.text_field :title,id: :gmap_title ,class: "form-control"%>
  </div>
  <div class="field form-group">
    <%= form.label :"コメント" ,class: "center-block"%><br>
    <%= form.text_area :coment, id: :gmap_coment ,size: "40x4",class: "form-control"%>
  </div>
  <div id="magic_w" class="field form-group">
    <%= form.label :"合言葉" ,class: "center-block"%>
    <%= form.text_field :magic_word,id: :magic_word ,class: "form-control"%>
  </div>
  <div class="field form-group">
    <%= form.label :"マーカーに載せる画像" ,class: "center-block"%>
    <%= form.file_field :image,id: :image ,class: "form-control"%>
  </div>
  <div class="actions">
    <%= form.submit class: "center-block"%>
  </div>
<% end %>
<br>
<div class="form-group text-center">
  <input type="checkbox" class="magic_c" name="magic_word_set" onclick="toggle('#magic_w', this)">全体に公開する
</div>
<div class="text-center">
  <%= link_to 'Back', root_path %>
</div>

app/views/gmaps/show.html.erb
<p>
  <strong>緯度:</strong>
  <%= @gmap.latitude %>
</p>

<p>
  <strong>経度:</strong>
  <%= @gmap.longitude %>
</p>

<p>
  <strong>コメント:</strong>
  <%= @gmap.coment %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @gmap.title %>
</p>

<%= link_to '編集する', edit_gmap_path(@gmap) %> |
<% end %>
<%= link_to '戻る', gmaps_path %>