config/routes.rb
Rails.application.routes.draw do
  root to: 'gmaps#index'
  devise_for :members
  get 'members/downloadpdf/download', to: 'members#downloadpdf'

  resources :members, only: [:show] do
    collection do
      get :search
      get :dispatching
    end
  end
  resources :gmaps do
    collection do
      get :confirm
      post :check
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/_aside.html.erb
<aside>
  <article>
    <% if member_signed_in? %>
      <h1 class="text-center">あなたの画像</h1>
      <br>
      <div class="text-center"><%= image_tag current_member.image ,class: :"img-rounded" %></div>
      <br>
      <div class="text-center"><%= current_member.name %></div>
      <br>
      <h1 class="text-center">絞り込み検索</h1>
      <%= form_tag({controller: "/members", action: "search",remote:true} ,{method: "get",id: "form1"}) do %>
        <div>
          <p>
            <label class="center-block">名前</label>
          </p>
        </div>
        <p>
          <input class="center-block" type="text" name="name" required="required"><br>
        </p>
        <div>
          <p>
            <label class="center-block">生年月日</label>
          </p>
        </div>
        <div class="center-block text-center">
            <%= select_date(Date.today,:start_year=> 1970,name: 'birth')  %>
        </div>
        <div>
          <p>
            <%= submit_tag '検索する', name: 'public' , class: "center-block" %>
          </p>
        </div>
      <% end %>

      <%= form_tag({controller: "/members", action: "search", remote: true} ,{method: "get", id: "form2"}) do %>
        <div>
          <p>
            <label class="center-block">メールアドレス</label>
          </p>
        </div>
        <div>
          <p>
            <input class="center-block" type="email" name="email" required="required"><br>
          </p>
        </div>
        <div class="center-block">
          <p>
            <label class="center-block">合言葉</label>
          </p>
        </div>
        <div>
          <p>
            <input class="center-block" type="text" name="magic_word" required="required">
          </p>
        </div>
        <div>
          <p><%= submit_tag '検索する', name: 'private', class: "center-block" %></p>
        </div>
     <% end %>
    <div class="form-group text-center">
      <div class="radio">
        <input type="radio" id="radio1" name="radio_serach" value="public" checked="checked">
        <strong>全体に公開されているものを検索</strong>
      </div>
      <div class="radio">
        <input type="radio" id="radio2" name="radio_serach" value="private">
        <strong>プライベートのものを検索</strong>
      </div>
    </div>
  <% else %>
    <div>
      <strong><%= link_to "最初にお読みください",{controller: "/members", action: "downloadpdf"} %></strong>
    </div>
    <div class="box22">
      <i class="fa fa-heart faa-pulse animated fa-example">
        <p>
          このサイトはGoogleMapを使って現在地にマーカーを立てられます。マーカーには写真とタイトルとコメントが載せられるよ<br>
          ログインすればプライベートなマーカーはメールアドレスと合言葉で、公開のもの氏名と年齢で検索できます。<br>
          自分以外の記事は削除できないよ楽しんでいってね！<br>
          ちなみにマーカーは作成後60日で自動的に削除されます。
        </p>
      </i>
    </div>
  <% end %>
</article>
</aside>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample3">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Gmaps",root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="navbarEexample3">
          <ul class="nav navbar-nav navbar-right">
            <% if member_signed_in? %>
              <li class="pull-right"><%= link_to "ログアウト", destroy_member_session_path, method: :delete %></li>
              <li class="pull-right"><%= link_to "プロフィール", member_path(current_member.id)  %></li>
            <% else %>
              <li class="pull-right"><%= link_to "ログイン", new_member_session_path %></li>
              <li class="pull-right"><%= link_to "新規登録", new_member_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>gmaps</title>
    <meta name="viewport" content="width=device-width">
    <script src="https://maps.google.com/maps/api/js?v3&key=AIzaSyBAWgF_RcfttdtN6-Q4RX9OsjiQ2hD5n98&callback=initMap" async="async" defer="defer"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="row">
      <div class="box col-xs-12 col-md-8">
        <%= yield %>
      </div>
      <div class="box col-xs-12 col-md-4">
        <%= render 'layouts/aside' %>
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted">Place sticky footer content here.</p>
    </div>
  </footer>
  <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('danger','error').gsub('alert','error').gsub('notice','info') %>
          toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    </script>
  <% end %>
  </body>
</html>